openapi: 3.0.0
info:
  title: WSO2 Identity Server - Endpoint Configuration Manager API Definition
  description: This document specifies a **RESTful API** for **WSO2 Identity Server endpoints configurations**
  contact:
    name: WSO2
    url: http://wso2.com/products/identity-server/
    email: architecture@wso2.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "v1"
servers:
  - url: https://localhost:9443/t/{tenant-domain}/api/server/v1
    variables:
      tenant-domain:
        default: carbon.super
security:
  - OAuth2: []
  - BasicAuth: []
paths:
  /endpoint-configurations:
    get:
      tags:
        - Configuration
      summary: Get a list of configured endpoints
      description: |
        This API provides the capability to retrieve the list of configured
        endponit URLs.
      operationId: getEndpointConfigurationList
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfiguredEndpointsList'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Configuration
      summary: Create an endpoint Configuration
      description: |
        This API provides the capability to create an endpoint configuration
      operationId: createEndpointConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/endpointConfigurationAdd'
            example:
              referenceName: sample-configuration
              url: 'https://sample.configuration'
              auth-type: gdxhgddgcgtsf
              secret:
                - key: api-key
                  value: jbbrbrbgtrgjklth

      responses:
        "201":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointConfiguration'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/endpoint-configurations/{reference-name}':
    get:
      tags:
        - Configuration
      summary: Retrieve endpoint configuration by reference name
      description: |
        This API provides the capability to retrieve an endpoint configuration
        by name.
      operationId: getEndpointConfiguration
      parameters:
        - name: reference-name
          in: path
          description: reference-name of the endpoint configuration
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointConfiguration'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Configuration
      summary: Update a endpoint configuration
      description: |
        This API provides the capability to update an endpoint configuration by
        reference-name.
      operationId: updateEndpointConfiguration
      parameters:
        - name: reference-name
          in: path
          description: reference-name of the endpoint configuration
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointConfigurationUpdateRequest'
            example:
              fromAddress: iam@gmail.com
              userName: iam
              password: iam123
              secret:
                - key: api-key
                  value: ertcfguuiccx

        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointConfiguration'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Configuration
      summary: Delete an endpoint confuguration by name
      description: |
        This API provides the capability to delete a endpoint configuration by
        name.
      operationId: deleteEndPointConfiguration
      parameters:
        - name: reference-name
          in: path
          description: reference-name of the endpoint configuration
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          example: NSM-00000
        message:
          type: string
          example: Some Error Message
        description:
          type: string
          example: Some Error Description
        traceId:
          type: string
          example: e0fbcfeb-3617-43c4-8dd0-7b7d38e13047
    endpointConfigurationAdd:
      required:
        - referenceName
        - url
        - auth-type
        - secret
      type: object
      properties:
        referenceName:
          type: string
        url:
          type: string
        auth-type:
          type: string
        secret:
          $ref: '#/components/schemas/Secret'

    EndpointConfiguration:
      required:
        - referenceName
        - url
        - auth-type
        - secret
      type: object
      properties:
        referenceName:
          type: string
        url:
          type: string
        auth-type:
          type: string
        secret:
          $ref: '#/components/schemas/Secret'


    EndpointConfigurationUpdateRequest:
      required:
        - referenceName
        - url
        - auth-type
      type: object
      properties:
        referenceName:
          type: string
        url:
          type: string
        auth-type:
          type: string
        secret:
          $ref: '#/components/schemas/Secret'

    Secret:
      type: object
      required:
        - key
        - value
      properties:
        key:
          type: string
          example: api-key
        value:
          type: string
          example: hsjsdjsadsahsahd

    ConfiguredEndpointsList:
      type: array
      items:
        $ref: '#/components/schemas/EndpointConfiguration'
  parameters:
    typeQueryParam:
      name: type
      in: query
      description: |
        Type of authenticators. Can be either 'LOCAL' or 'REQUEST_PATH'
      required: false
      style: form
      explode: true
      schema:
        type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://localhost:9443/oauth2/authorize
          tokenUrl: https://localhost:9443/oauth2/token
          scopes: {}
