openapi: 3.0.0
info:
  title: "WSO2 Identity Server - Choreo Account Associations API Definition"
  description: This document specifies a **RESTful API** for **WSO2 Identity Server Choreo configurations**
  contact:
    name: WSO2
    url: http://wso2.com/products/identity-server/
    email: architecture@wso2.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "v1"
servers:
  - url: https://localhost:9443/t/{tenant-domain}/api/server/v1
    variables:
      tenant-domain:
        default: carbon.super
security:
  - OAuth2: []
  - BasicAuth: []
paths:
  /ChoreoConfigurations:
    get:
      tags:
        - Choreo
      summary: Get a list of choreo configured endpoints
      description: |
        This API provides the capability to retrieve the list of choreo configured URLs.
      operationId: getChoreoConfigurationList
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfiguredChoreoURLList'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Choreo
      summary: Create an choreo Configuration
      description: |
        This API provides the capability to create an Choreo configuration
      operationId: createChoreoConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChoreoConfiugurationAdd'
            example:
              refereneceName: iam@gmail.com
              url: iam@gmail.com
              api-key: iam
      responses:
        "201":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Choreoconfiguration'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /ChoreoConfigurations/{reference-name}:
    get:
      tags:
        - Choreo
      summary: Retrieve Choreo configuration by reference name
      description: |
        This API provides the capability to retrieve an Choreo configuration by name.
      operationId: getChoreoConfiguration
      parameters:
        - name: reference-name
          in: path
          description: reference-name of the choreo endpoint
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Choreoconfiguration'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Choreo
      summary: Update a Choreo configuration
      description: |
        This API provides the capability to update an Choreo configuration by reference-name.
      operationId: updateChoreoConfiguration
      parameters:
        - name: reference-name
          in: path
          description: reference-name of the choreo endpoint
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChoreoconfigurationUpdateRequest'
            example:
              fromAddress: iam@gmail.com
              userName: iam
              password: iam123
              properties:
                - key: mail.smtp.starttls.enable
                  value: true
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Choreoconfiguration'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Choreo
      summary: Delete an choreo confuguration by name
      description: |
        This API provides the capability to delete a Choreo configuration by name.
      operationId: deleteChoreoConfiguration
      parameters:
        - name: reference-name
          in: path
          description: reference-name of the choreo endpoint
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          example: NSM-00000
        message:
          type: string
          example: Some Error Message
        description:
          type: string
          example: Some Error Description
        traceId:
          type: string
          example: e0fbcfeb-3617-43c4-8dd0-7b7d38e13047

    ChoreoConfiugurationAdd:
      required:
        - refereneceName
        - url
        - api-key
      type: object
      properties:
        refereneceName:
          type: string
        url:
          type: string
        api-key:
          type: string

    Choreoconfiguration:
      required:
        - refereneceName
        - url
        - api-key
      type: object
      properties:
        refereneceName:
          type: string
        url:
          type: string
        api-key:
          type: string


    ChoreoconfigurationUpdateRequest:
      required:
        - refereneceName
        - url
        - api-key
      type: object
      properties:
        refereneceName:
          type: string
        url:
          type: string
        api-key:
          type: string

    ConfiguredChoreoURLList:
      type: array
      items:
        $ref: '#/components/schemas/Choreoconfiguration'

  parameters:
    typeQueryParam:
      name: type
      in: query
      description: |
        Type of authenticators. Can be either 'LOCAL' or 'REQUEST_PATH'
      required: false
      style: form
      explode: true
      schema:
        type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://localhost:9443/oauth2/authorize
          tokenUrl: https://localhost:9443/oauth2/token
          scopes: {}
